### ISSUE TITLE
Magento: Where is the Larryn Magento API Extension?

### ISSUE THREAD

**Issue by davidonelson** [connectedbusiness/eshopconnected#9]
This is mentioned in source file MagentoSOAPConnector.vb in function CheckCustomAPIWorking.  It seems to be additional APIs installed on the Magento side to make interfacing with Magento easier/faster

**Comment by ramildomingo** [comment]
Based on the code review I did, this function seems to just validate if the xml data is in a valid format.  There does not seem to be any special function that indicates about a Magento Extension to be installed on the Magento Site.

Look for this code function and notice that it just checks for existing elements inside the response data from the SOAP call from Magento.

Private Function CheckCustomAPIWorking() As Boolean

**Comment by davidonelson** [comment]
Function CheckCustomAPIWorking is one minor piece of the puzzle.  Search MagentoSOAPConnector.vb for these strings:   "Lerryn_LBSapi"  and  "Lerryn_Ldtapi"

All of these functions use the custom API:
•	GetAPIVersion
•	GetMagentoVersion
•	GetCatalogProductListMaxID
•	GetCatalogProductListBatch
•	GetAllProductDetails_SOAP
•	GetConfigurableProductAttributes
•	GetCatalogRelatedProducts
•	GetCatalogProductCustomOptions
•	GetProductAttributes
•	GetStoreList
•	GetAttributeTable
•	LinkConfigWithSimpleProducts
•	GetAttributeList
•	GetAllAttributeValues
•	GetAttributeTimestamp

As GetAPIVersion is called in the Login procedure, and it fails if the custom API is not installed, I could not get the Login procedure to successfully function, until I commented out some code.

**Comment by ramildomingo** [comment]
I did not find anything from the repository related to this.  We might need to reach out to Lerryn.

**Comment by davidonelson** [comment]
The needed files have been located in this folder of the repository:
trunk\ClientDeployment\Lerryn.InstallerSetup.eShopCONNECT
